name: Dimetra-user CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3
    
    # Setup Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Set up environment variables
    - run: |
        touch .env
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
    
    # Install node_modules
    - name: Install Dependencies
      run: npm ci  # or npm install if you don’t use package-lock.json

    # Restart the PM2 process after dependencies are installed
    # - name: Restart PM2 Process
    #   run: pm2 restart dimetra-bakend
